### ISSUE TITLE
Active Directory groups are Static

### ISSUE THREAD

**Issue by jtreen** [theopenem/Toems#7]
Because AD groups are static, when adding or removing machines from groups within AD itself after the initial import, this does not seem to replicate to Toems even after a manual LDAP sync. Can AD groups be dynamic?

**Comment by theopenem** [comment]
Just saw this.  The forums are a better place to reach out.  I'll look into this issue.

**Comment by theopenem** [comment]
I have not been able to replicate this issue.  The AD groups continue to update / add / remove computers each time the sync is ran.
