### ISSUE TITLE
JQuery 1.2 < 3.5.0 Multiple XSS

### ISSUE THREAD

**Issue by felixtech-msp** [theopenem/Toems#9]
According to the self-reported version in the script, the version of JQuery hosted on the remote web server is greater than or equal to 1.2 and prior to 3.5.0. It is, therefore, affected by multiple cross site scripting vulnerabilities.
`/content/js/jquery-3.2.1.min.js`

**Comment by theopenem** [comment]
Thanks.  Updated.
https://github.com/theopenem/Toems/commit/faccd5edd2fbee8be29a76e482397589f0779d0f
